name: test
on:
  push:
    paths-ignore:
      - .flake8
      - .gitignore
      - .pre-commit-config.yaml
      - LICENSE.md
      - README.md
    branches:
      - '**'
jobs:
  tests:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.9']
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - python ${{ matrix.python-version }}
    env:
      coverage: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached Poetry environment
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ matrix.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --only main,test --no-root
      - name: Install library
        run: poetry install --no-interaction --only-root
      - name: Run tests
        if: env.coverage != 'true'
        run: poetry run pytest --doctest-modules src tests
      - name: Run tests (with coverage)
        if: env.coverage == 'true'
        run: poetry run pytest --doctest-modules src tests --cov=src --cov-report xml
      - name: Upload coverage to Codecov
        if: env.coverage == 'true'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
